export * from './home/homePage.component'
export * from './about-us/aboutUsPage.component'
export * from './policies/policiesPage.component'
export * from './shipping/shippingPage.component'
export * from './faq/faqPage.component'